### PR TITLE
VideoManager: Remove unused/incorrect override

### PR DESCRIPTION
**Pull request by Ryanf55**
## Description
Fixes a compilation error on Ubuntu 22 introduced by https://github.com/mavlink/qgroundcontrol/pull/14332.
This function is not used in the codebase, so it can just be removed.

```
/home/ryan/Dev/qgroundcontrol/src/VideoManager/VideoReceiver/GStreamer/HwBuffers/GstDmaBufVideoBuffer.h:27:10: error: ‘bool GstDmaBufVideoBuffer::isDmaBuf() const’ marked ‘override’, but does not override
   27 |     bool isDmaBuf() const override { return true; }
```
   
   

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] CI/Build changes
- [ ] Other

## Testing

- [x] Tested locally
- [ ] Added/updated unit tests
- [ ] Tested with simulator (SITL)
- [ ] Tested with hardware

### Platforms Tested

- [x] Linux
- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS

### Flight Stacks Tested

- [ ] PX4
- [ ] ArduPilot

## Checklist

- [x] I have read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I have read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] My code follows the project's coding standards
- [ ] I have added tests that prove my fix/feature works
- [x] New and existing unit tests pass locally

## Related Issues

---
By submitting this pull request, I confirm that my contribution is made under the terms of the project's dual license (Apache 2.0 and GPL v3).

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Superseded by #14589, which re-applies the same change on top of the GStreamer backend overhaul that relocated the file. Thanks @Ryanf55 — credited in the new PR.

**Comment by DonLakeFlyer** [comment]
I closed mine and reopened this one. @HTRamsey Now sure what to do with this?

**Comment by DonLakeFlyer** [comment]
Thanks for the report, but the "Ubuntu 22" attribution is coincidental — this error is Qt-version-dependent, not OS-dependent.

`GstDmaBufVideoBuffer` inherits `GstHwVideoBuffer`, which derives from Qt's private `QHwVideoBuffer` (`private/qhwvideobuffer_p.h`). The `virtual bool isDmaBuf() const` lives in that Qt private header (present in Qt 6.11.1). Whether the `override` compiles depends entirely on which Qt you build against, not which Ubuntu you build on — our 22.04 Docker/CI builds pass because they install the pinned Qt via aqt rather than using the distro Qt.

The failure here comes from building against an older local Qt where `QHwVideoBuffer::isDmaBuf()` doesn't exist yet. Building with the Qt version QGC pins resolves it.

Also, removing the override isn't quite safe: `isDmaBuf()` is called by Qt Multimedia internally, so dropping it would make DMABuf frames report `false` and could silently disable Qt's internal DMABuf handling.

Closing since this isn't reproducible with the supported Qt version.
